
export const authConfig = {
  verifyEmailEndpoint: `${import.meta.env.VITE_API_URL}/api/auth/verify-email`,
  loginEndpoint: `${import.meta.env.VITE_API_URL}/api/auth/login`,
  registerEndpoint: `${import.meta.env.VITE_API_URL}/api/auth/register`,
  changePasswordEndpoint: `${import.meta.env.VITE_API_URL}/api/auth/change-password`,
  labels: {
    emailPlaceholder: "Email",
    passwordPlaceholder: "Password",
    emailButton: "Next",
    passwordButton: "Login",
    invalidEmail: "Email not found",
    back: "Back",
    namePlaceholder: "Name",
    fathernamePlaceholder: "Father name",
    mothernamePlaceholder: "Mother name",
    countryPlaceholder: "Country",
    birthdatePlaceholder: "Birthdate",
    cellphonePlaceholder: "Cellphone",
    agePlaceholder: "Age",
    genderPlaceholder: "Gender",
    registerButton: "Register",
    validEmail: "Email already exists",
  },
  onSuccess: (token: string) => console.log("Logged in", token),
  onError: (msg: string) => console.error(msg),
};
